# Generated by Django 4.1.3 on 2022-12-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
    ]
