# Generated by Django 4.1.4 on 2023-06-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_qrcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcode",
            name="background",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], default=False
            ),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="background_color",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="border",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], default=False
            ),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="border_color",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="encryption_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WEP", "WEP"),
                    ("WPA", "WPA"),
                    ("WPA2-EAP", "WPA2-EAP"),
                    ("no pass", "no pass"),
                ],
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="frame_style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("frame1", "Frame 1"),
                    ("frame2", "Frame 2"),
                    ("frame3", "Frame 3"),
                    ("frame4", "Frame 4"),
                ],
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="hidden_network",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="name",
            field=models.CharField(default="QR Code", max_length=255),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="network_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="network_password",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="qr_style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("style1", "Style 1"),
                    ("style2", "Style 2"),
                    ("style3", "Style 3"),
                    ("style4", "Style 4"),
                ],
                max_length=6,
            ),
        ),
    ]
