# Generated by Django 4.1.4 on 2023-07-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_user_bio_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='short_url',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
