# Generated by Django 4.1.4 on 2023-07-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_qrcode_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='times_scanned',
            field=models.IntegerField(default=0),
        ),
    ]
