# Generated by Django 4.1.4 on 2023-07-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_qrcode_times_scanned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='times_scanned',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
