# Generated by Django 4.1.4 on 2023-07-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_alter_qrcode_times_scanned"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("message", models.TextField(blank=True)),
                ("contact_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="qrcode",
            name="background",
        ),
        migrations.RemoveField(
            model_name="qrcode",
            name="background_color",
        ),
        migrations.RemoveField(
            model_name="qrcode",
            name="border",
        ),
        migrations.RemoveField(
            model_name="qrcode",
            name="border_color",
        ),
        migrations.RemoveField(
            model_name="qrcode",
            name="encryption_type",
        ),
        migrations.RemoveField(
            model_name="qrcode",
            name="frame_style",
        ),
        migrations.RemoveField(
            model_name="qrcode",
            name="hidden_network",
        ),
        migrations.RemoveField(
            model_name="qrcode",
            name="network_name",
        ),
        migrations.RemoveField(
            model_name="qrcode",
            name="network_password",
        ),
        migrations.RemoveField(
            model_name="qrcode",
            name="qr_style",
        ),
    ]
