# Generated by Django 3.1.4 on 2020-12-10 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bids_comments_watchlists'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Listings',
            new_name='Listing',
        ),
        migrations.RenameModel(
            old_name='WatchLists',
            new_name='WatchList',
        ),
    ]
